apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: '1.2.3'
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      interval: 1m